baseURL = "https://blog.fukkatsuso.com/"
languageCode = "ja"
DefaultContentLanguage = "ja"
title = "復活草のブログ"
theme = "hugo-notepadium"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true 

[params]
style = "light"

[params.syntax]
use = "none"

[params.nav]
showCategories = true
showTags = true