services:
  hugo:
    build:
      context: ./
      args:
        - HUGO_VERSION=v${HUGO_VERSION}
    container_name: hugo
    tty: true
    volumes:
      - ./:/go/src/github.com/Fukkatsuso/blog
    ports:
      - 1313:1313
    command: hugo server --bind=0.0.0.0 -D
