name: Deploy

on:
  push:
    branches:
      - master

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
        with:
          submodules: true
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.3'

      - name: Build
        run: hugo --minify
      
      - name: GCP Authenticate
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: $GCP_SA_KEY
          export_default_credentials: true

      - name: Deploy to GAE
        uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
        with:
          project_id: $GCP_PROJECT